
import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";

const fontMono = Ubuntu({
  variable: "--font-mono",
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${fontMono.variable} antialiased`}>{children}</body>
    </html>
  );
}